import Foundation

/// Finds the resource bundle for the SDK.
/// Works with both SPM and CocoaPods.
enum SezzleBundle {
    nonisolated(unsafe) static let resourceBundle: Bundle = {
        // 1. CocoaPods: resource_bundles creates a .bundle inside the framework
        let frameworkBundle = Bundle(for: SezzlePromotionalView.self)
        if let podBundleURL = frameworkBundle.url(forResource: "SezzleMerchantSDK", withExtension: "bundle"),
           let podBundle = Bundle(url: podBundleURL) {
            return podBundle
        }

        // 2. SPM: resources are in the module bundle
        //    Bundle.module is auto-generated by SPM — find it by looking for our resource
        let candidates = [
            frameworkBundle,
            Bundle.main,
        ]
        for bundle in candidates {
            if bundle.url(forResource: "sezzle_logo", withExtension: "png") != nil {
                return bundle
            }
        }

        return frameworkBundle
    }()
}
