name: SezzleCheckoutExample
options:
  bundleIdPrefix: com.sezzle.example
  deploymentTarget:
    iOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 3FQLS4W4NS
    TARGETED_DEVICE_FAMILY: "1"
packages:
  SezzleMerchantSDK:
    path: ../
targets:
  SezzleCheckoutExample:
    type: application
    platform: iOS
    sources:
      - SezzleCheckoutExample
    dependencies:
      - package: SezzleMerchantSDK
    info:
      path: SezzleCheckoutExample/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen: {}
